### ISSUE TITLE
Slim3

### ISSUE THREAD

**Issue by bobinrinder** [amenadiel/SlimPHPConsole#1]
Hi,

composer says the newest versions aren't working with Slim 3, maybe you can consider changing this. ;-)

Cheers,
Robin

**Comment by adrienlamotte** [comment]
+1 ;)

**Comment by ffflabs** [comment]
I'll try to get it working with slim3 to see if It's safe to relax the version restriction. 

This bridge does so little that it might work as it is.

**Comment by ffflabs** [comment]
Update:

I'm using slim3 for my current project to things are gonna catch upbafyer all
